//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logoped1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspisanie
    {
        public int ID { get; set; }
        public string DayOfWeek { get; set; }
        public int Zagruzka { get; set; }
        public string ThemeLesson { get; set; }
        public string StudentList { get; set; }
        public string Group { get; set; }
        public string Class { get; set; }
        public int IDTeacher { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
