//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logoped1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public Nullable<bool> Parents { get; set; }
        public string Phone { get; set; }
        public Nullable<double> SredniyBal { get; set; }
        public int IdTeacher { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
